twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: d.m.Y
        timezone: Europe/Chisinau
    globals:
        google_maps_api_key: '%google_maps_api_key%'
        competence_use_multiplication_factor: !php/const App\Consts::COMPETENCE_USE_MULTIPLICATION_FACTOR
        google_analytics_key: '%env(GOOGLE_ANALYTICS_KEY)%'
        org_name: '%app_org_name%'
