twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: d.m.Y
        timezone: Europe/Chisinau
    globals:
        google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
        google_analytics_key: '%env(default::GOOGLE_ANALYTICS_KEY)%'
        google_tag_manager_id: '%env(default::GOOGLE_TAG_MANAGER_ID)%'
        hotjar_id: '%env(default::HOTJAR_ID)%'
        algolia_app_id: '%env(default::ALGOLIA_APP_ID)%'
        algolia_public_api_key: '%env(default::ALGOLIA_PUBLIC_API_KEY)%'
        competence_use_multiplication_factor: !php/const App\Consts::COMPETENCE_USE_MULTIPLICATION_FACTOR
        org_name: '%app_org_name%'
