language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - TEST_DATABASE_URL=pgsql://postgres:@localhost:5432/defacto_test

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database defacto_test;' -U postgres

before_install:
  - composer self-update

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit
  # this checks that the composer.json and composer.lock files are valid
  - composer validate --strict
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
