language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - DATABASE_URL=pgsql://postgres:@localhost:5432/defacto_test

matrix:
  fast_finish: true
  include:
    - php: 7.3

services:
  - postgresql

addons:
  postgresql: "9.4"
  apt:
    update: true

before_script:
  - psql -c 'create database defacto_test;' -U postgres

before_install:
  - composer self-update

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - mkdir -p public/build && echo '{}' > public/build/manifest.json
  - ./vendor/bin/simple-phpunit
  - composer validate
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
