version: '3.4'

services:
    defacto_php:
        container_name: defacto_php
        image: defacto_php
        build:
            context: .
        volumes:
            - ./.volumes/php/sock:/sock
            - ./.volumes/php/conf:/usr/local/etc/php-fpm.d:ro
            - ../vendor:/www/vendor:ro
            - ../config:/www/config:ro
            - ../public:/www/public:ro
            - ../src:/www/src:ro
            - ../templates:/www/templates:ro
            - ../.env:/www/.env:ro
            - ../uploads:/www/uploads:rw
        command: ["-F"]
    defacto_pg:
        container_name: defacto_pg
        image: postgres:9
        volumes:
            - ./.volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
        restart: unless-stopped
    defacto_backup_pg:
        container_name: defacto_backup_pg
        image: postgres:9
        depends_on:
            - defacto_pg
        volumes:
            - ./.volumes/backup/postgres:/backups
            - ./.volumes/backup/postgres.sh:/entrypoint.sh:ro
            - ../backup/postgres/pg_backup_rotated.sh:/backup/pg_backup_rotated.sh:ro
            - ../backup/postgres/pg_backup.config:/backup/pg_backup.config:ro
            - ../backup/postgres/.pgpass:/backup/.pgpass:ro
        entrypoint: ["/entrypoint.sh"]
        restart: unless-stopped
    defacto_backup_uploads:
        container_name: defacto_backup_uploads
        image: ubuntu:18.04
        volumes:
            - ../uploads:/uploads:ro
            - ./.volumes/backup/uploads:/backups
            - ./.volumes/backup/uploads.sh:/entrypoint.sh:ro
            - ../backup/uploads/backup_rotated.sh:/backup.sh:ro
        entrypoint: ["/entrypoint.sh"]
        restart: unless-stopped
    defacto_sync:
        container_name: defacto_sync
        image: resilio/sync
        ports:
            - 8800:8888
        volumes:
            - ./.volumes/sync:/mnt/sync
            - ./.volumes/backup:/mnt/mounted_folders/backup/backups:ro
        command: ["--config", "/mnt/sync/sync.conf", "--log", "/mnt/sync/sync.log"]

# Add in `docker-compose.override.yml`
#
#    defacto_adminer:
#        container_name: defacto_adminer
#        image: adminer
#        ports:
#            - 8080:8080
#        restart: unless-stopped
