version: '3.4'

services:
    defacto: # just to build the image, then run `./x11docker ~/path/to/ide.sh`
        container_name: defacto
        image: defacto
        build:
            context: .
    defacto_pg:
        container_name: defacto_pg
        image: postgres:9
        volumes:
            - ./.volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
        restart: unless-stopped
    defacto_adminer:
        container_name: defacto_adminer
        image: adminer
        ports:
            - 8080:8080
        restart: unless-stopped
