version: '3.4'

x-custom:
    cmd: &user-create-cmd >-
        bash -c '(
        adduser --gecos 0 --disabled-password
        --home ${HOME} --uid ${UID:-1000} ${USER}
        || true
        )
        &&
        tail -f /dev/null'

services:
    defacto:
        container_name: defacto
        image: defacto
        build: .
        volumes:
            - ${HOME}:${HOME}
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            DISPLAY: ${DISPLAY}
        cap_add:
            - SYS_PTRACE # for debugger
        working_dir: ${PWD}/..
        ports:
            - 80:8080
        entrypoint: []
        command: *user-create-cmd
    defacto_js:
        container_name: defacto_js
        image: node:9.3
        volumes:
            - ..:/app
        working_dir: /app
        entrypoint: []
        command: *user-create-cmd
    defacto_pg:
        container_name: defacto_pg
        image: postgres:10.1
        restart: always
        volumes:
            - ./.volumes/pg:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
    defacto_adminer:
        container_name: defacto_adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080