version: '3.4'

volumes:
    postgres:
    sync:

services:
    defacto_php:
        container_name: defacto_php
        image: defacto_php
        build:
            context: .
        volumes:
            - ./.volumes/php/sock:/sock
            - ./.volumes/php/conf:/usr/local/etc/php-fpm.d:ro
            - ../vendor:/var/www/vendor:ro
            - ../composer.json:/var/www/composer.json:ro
            - ../config:/var/www/config:ro
            - ../public:/var/www/public:ro
            - ../src:/var/www/src:ro
            - ../templates:/var/www/templates:ro
            - ../translations:/var/www/translations:ro
            - ../.env:/var/www/.env:ro
            - ../uploads:/var/www/uploads:rw
            - ../var:/var/www/var:rw
        command: ["-F"]
        restart: unless-stopped
    defacto_pg:
        container_name: defacto_pg
        image: postgres:9
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
        restart: unless-stopped
    defacto_backup_pg:
        container_name: defacto_backup_pg
        image: postgres:9
        depends_on:
            - defacto_pg
        volumes:
            - ./.volumes/backup/postgres:/backups
            - ./.volumes/backup/postgres.sh:/entrypoint.sh:ro
            - ../backup/postgres/pg_backup_rotated.sh:/backup/pg_backup_rotated.sh:ro
            - ../backup/postgres/pg_backup.config:/backup/pg_backup.config:ro
            - ../backup/postgres/.pgpass:/backup/.pgpass:ro
        entrypoint: ["/entrypoint.sh"]
        restart: unless-stopped
    defacto_backup_uploads:
        container_name: defacto_backup_uploads
        image: ubuntu:18.04
        volumes:
            - ../uploads:/uploads:ro
            - ./.volumes/backup/uploads:/backups
            - ./.volumes/backup/uploads.sh:/entrypoint.sh:ro
            - ../backup/uploads/backup_rotated.sh:/backup.sh:ro
        entrypoint: ["/entrypoint.sh"]
        restart: unless-stopped
    defacto_sync:
        container_name: defacto_sync
        image: resilio/sync
        ports:
            - 8800:8888
        volumes:
            - sync:/mnt/sync
            - ./.volumes/backup/postgres:/mnt/mounted_folders/backup/backups/postgres:ro
            - ./.volumes/backup/uploads:/mnt/mounted_folders/backup/backups/uploads:ro
        command: ["--config", "/mnt/sync/sync.conf", "--log", "/mnt/sync/sync.log"]
        restart: unless-stopped

# Add in `docker-compose.override.yml`
#
#    defacto_adminer:
#        container_name: defacto_adminer
#        image: adminer
#        ports:
#            - 8080:8080
#        restart: unless-stopped
