version: '3.4'

services:
    defacto:
        container_name: defacto
        image: defacto:1.1
        build:
            context: .
        volumes:
            - ${HOME}:${HOME}
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            DISPLAY: ${DISPLAY}
        cap_add:
            - SYS_PTRACE # for debugger
        working_dir: ${PWD}/..
        ports:
            - 80:8080
        depends_on:
            - defacto_pg
    defacto_pg:
        container_name: defacto_pg
        image: postgres:9
        volumes:
            - ./.volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
    defacto_adminer:
        container_name: defacto_adminer
        image: adminer
        ports:
            - 8080:8080