version: '3.4'

volumes:
    php_sock:
    postgres:
    backup:

services:
    defacto_php:
        container_name: defacto_php
        image: defacto_php
        build:
            context: .
        volumes:
            - php_sock:/sock
            - ./php-fpm.d:/usr/local/etc/php-fpm.d:ro
            - ../vendor:/var/www/vendor:ro
            - ../composer.json:/var/www/composer.json:ro
            - ../config:/var/www/config:ro
            - ../public:/var/www/public:ro
            - ../src:/var/www/src:ro
            - ../templates:/var/www/templates:ro
            - ../translations:/var/www/translations:ro
            - ../.env.dist:/var/www/.env:ro
            - ../uploads:/var/www/uploads:rw
            - ../var:/var/www/var:rw
        command: ["-F"]
        restart: unless-stopped
    defacto_pg:
        container_name: defacto_pg
        image: postgres:9
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "defacto"
            POSTGRES_PASSWORD: "defacto"
            POSTGRES_DB: "defacto"
        restart: unless-stopped
    defacto_resilio:
        container_name: defacto_resilio
        image: resilio/sync
        volumes:
            - backup:/mnt/mounted_folders/sync/archives:ro
            - ./resilio/sync.conf.template:/etc/sync.conf.template:ro
            - ./resilio/entrypoint.sh:/sbin/entrypoint.sh:ro
            - ./secrets/resilio/secret.dist:/run/secrets/resilio:ro
        entrypoint: ["entrypoint.sh"]
        command: ["--config", "/etc/sync.conf"]
        restart: unless-stopped
