#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_DIR=$(dirname ${SCRIPT_DIR})
CMD=${@}

docker run -it --rm -u ${UID} \
    -v ${PROJECT_DIR}:${PROJECT_DIR} \
    node:9 \
    bash -c "cd ${PROJECT_DIR} && ${CMD}"
