#!/bin/bash

[ -n "$(which x11docker)" ] \
    || { echo "x11docker is required"; exit 1; }

CMD=${@}
[ -n "${CMD}" ] \
    || { echo "Command is required"; exit 1; }

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
PROJECT_DIR=$(dirname ${SCRIPT_DIR})
IMAGE=defacto
NETWORK=defacto_default

[ -n "$(docker images -q --filter=reference="${IMAGE}")" ] \
    || docker build -t ${IMAGE} ${SCRIPT_DIR}

[ -n "$(docker network ls -q --filter name=${NETWORK})" ] \
    || docker-compose -f ${SCRIPT_DIR}/docker-compose.yml up -d

x11docker --hostdisplay --homedir ${HOME} --clipboard --stdout --stderr \
    --cap-default --no-init --workdir ${PROJECT_DIR} \
    -- "--cap-add=SYS_PTRACE --publish=80:8080 --network ${NETWORK}" \
    ${IMAGE} ${CMD}
