#!/bin/bash

[ -n "$(which x11docker)" ] \
    || { echo "x11docker is required"; exit 1; }

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
PROJECT_DIR=$(dirname ${SCRIPT_DIR})
CMD=${@}

CMD=${@}
[ -n "${CMD}" ] \
    || { echo "Command is required"; exit 1; }

IMAGE=defacto

[ -n "$(docker images -q --filter=reference="${IMAGE}")" ] \
    || docker build -t ${IMAGE} ${SCRIPT_DIR}

x11docker --hostdisplay --homedir ${HOME} --clipboard --stdout --stderr \
    --cap-default --no-init --workdir ${PROJECT_DIR} \
    -- "--cap-add=SYS_PTRACE --publish=80:8080 --network defacto_default" \
    ${IMAGE} \
    ${CMD}
