#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
PROJECT_DIR=$(dirname ${SCRIPT_DIR})
CMD=${@}

x11docker --hostdisplay --homedir ${HOME} --clipboard \
    --cap-default --no-entrypoint \
    -- "--cap-add=SYS_PTRACE --publish=80:8080 --network defacto_default" \
    defacto \
    ${CMD}
